apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-gui
  description: Tanzu Application Platform GUI Component
  tags:
    - v1alpha1
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=backstage'
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: tap-gui