apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: roy
spec:
  profile:
    displayName: Roy Sharon
    email: roy@terasky.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [it-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: adiel
spec:
  profile:
    displayName: Adiel Gilboa
    email: adiel@terasky.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [it-team]